<document> ::= { <element> }
<element>  ::= <element-named> | <element-text> | <element-implicit-div>
<element-named> ::= NAME <element-named-rest>
<element-implicit-div> ::= CLASS <element-named-rest>
<element-named-rest> ::= { CLASS } [ <content> ]
<element-text>  ::= [ TEXT ] <text-body>
<text-body> ::= "(" TOKENS ")"
<content>  ::= "{" { <element> } "}" | <text-body>