<document> ::= { <element> }
<element>  ::= <element-named> | <element-text>
<element-named> ::= NAME { CLASS } [ <content> ]
<element-text>  ::= [ TEXT ] <text-body>
<text-body> ::= "(" TOKENS ")"
<content>  ::= "{" { <element> } "}" | <text-body>